#! /usr/bin/python

import ephem, cgi, os, re
from datetime import datetime
from pytz import timezone


def getRiseSet(body,obs,lat,long,date):
    obs.lat = lat
    obs.long = long
    obs.date = date + " 12:00"
    rise = obs.previous_rising(body)
    set = obs.next_setting(body)
    return [rise, set]

def ephemDateWithTZ(ephemDate, tzname):
    d = ephemDate.datetime().replace(tzinfo=timezone('UTC'))
    return d.astimezone(timezone('US/Eastern'))

def getRiseSetTable(year, lat, lon, tzname):
    fmt = "%Y-%m-%d--%H-%M-%S"
    sun = ephem.Sun()
    obs = ephem.Observer()
    obs.pressure = 0
    obs.horizon = '-0:34'
    table = []
    for month in range(0,12):
        for day in range(0,31):
            rise, set = getRiseSet(sun, obs, lat, lon, "%s/%1d/%1d" % (year,month+1,day+1))
            table.append( [ephemDateWithTZ(rise, tzname).strftime(fmt),
                          ephemDateWithTZ(set, tzname).strftime(fmt)] )
    return table


def printRiseSetTable(year, lat,lon,tzname):
    table = getRiseSetTable(year, lat, lon, tzname)
    print "# Sunrise/Sunset for %s,%s [timezone: %s]" % (lat,lon,tzname)
    for t in table:
        print "%s,%s" % (t[0], t[1])

print "Content-type: text/plain\n"

year,lat,lon,tzname = re.sub(r'^/', '', os.environ['PATH_INFO']).split(",")

printRiseSetTable(year, lat, lon, tzname)
